# Generated by Django 5.2.7 on 2025-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='id_proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
