# Generated by Django 5.2.7 on 2026-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialservicio',
            name='es_predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
