# Generated by Django 5.2.7 on 2026-02-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_materialservicio_es_predeterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
